version: '3.8'

services:

  frontend:
    build:
      context: ./
      args:
        - VITE_API_URL=
        - VITE_BEARER_TOKEN=
    image: blueimpact-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - proxy

  backend:
    build: ./Backend
    image: blueimpact-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/database:/Backend/database
      - ./Backend/media/projects:/Backend/media/projects
      - ./Backend/media/publications:/Backend/media/publications
      - ./Backend/staticfiles:/Backend/staticfiles
    env_file:
      - ./Backend/.env
    networks:
      - proxy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Backend/staticfiles:/static
      - ./Backend/media:/media
      - ./dist:/usr/share/nginx/html
      - ./certs:/etc/letsencrypt/live/blueimpact.eco.br:ro
    depends_on:
      - backend
    networks:
      - proxy

networks:
  proxy:
    driver: bridge