services:
  frontend:
    build:
      context: ./
      args:
        - VITE_API_URL=
        - VITE_BEARER_TOKEN=
    image: blueimpact-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - proxy

  backend:
    build: ./Backend
    image: blueimpact-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/database:/Backend/database
      - ./Backend/media/projects:/Backend/media/projects
      - ./Backend/media/publications:/Backend/media/publications
    networks:
      - proxy

networks:
  proxy:
    driver: bridge