services:
  backend:
    build: ./Backend
    image: blueimpact-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/database:/Backend/database
      - ./Backend/media/projects:/Backend/media/projects
      - ./Backend/media/publications:/Backend/media/publications
      - ./Backend/staticfiles:/Backend/staticfiles
    env_file:
      - ./Backend/.env
    networks:
      - proxy

  nginx:
    build:
      context: ./
      args:
        - VITE_API_URL=
        - VITE_BEARER_TOKEN=
    image: blueimpact-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Backend/staticfiles:/staticfiles
      - ./Backend/media:/media
      # Mapear certificados do host (onde existem) para o container
      - /etc/letsencrypt/live/blueimpact.eco.br:/etc/letsencrypt/live/blueimpact.eco.br:ro
      - /etc/letsencrypt/archive/blueimpact.eco.br:/etc/letsencrypt/archive/blueimpact.eco.br:ro
      # Volume para validação do Certbot
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - backend
    networks:
      - proxy

  # Serviço Certbot para obtenção e renovação de certificados
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

