# Generated by Django 4.2.20 on 2025-04-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_publication_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='file',
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
    ]
