# Generated by Django 4.2.20 on 2025-04-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_project_file_remove_publication_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
