# Generated by Django 4.2.20 on 2025-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
